dist: trusty
language: php

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

php:
  - 7.1

env:
  - VERSION=HEAD
  - VERSION=3.4.0
  # The final CI slot should be used to test the update path from the oldest
  # available database fixture.
  - VERSION=2.0.0

addons:
  chrome: stable

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - google-chrome-stable --version

install:
  # Clone ORCA so it can build the code base.
  - git clone --depth 1 git@github.com:acquia/orca.git ../orca

  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, Behat, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/../orca-build/vendor/bin:$PATH"
  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1
  # Install Prestissimo to speed up Composer a bit.
  - composer global require hirak/prestissimo

  # Install the PECL YAML extension for strict parsing. yes is used to
  # acknowledge all prompts.
  - pecl channel-update pecl.php.net
  - yes '' | pecl install yaml
  # Tweak PHP configuration.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Use ORCA to build the code base.
  - cd ../orca
  - composer install
  - ./bin/orca fixture:init -f --sut drupal/lightning_core --sut-only

before_script:
  - cd ../orca-build/docroot
  - $TRAVIS_BUILD_DIR/update.sh $VERSION
  - cd ../../orca

script:
  - ./bin/orca tests:run

after_failure:
  - cd ../orca-build/docroot
  - drush watchdog:show --count=100 --severity=Error --extended
