dist: trusty
language: php

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 7.1

env:
  - VERSION=HEAD
  - VERSION=3.4.0
  # The final CI slot should be used to test the update path from the oldest
  # available database fixture.
  - VERSION=1.0.0-rc2

addons:
  chrome: stable

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - google-chrome-stable --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # Install the PECL YAML extension for strict parsing. yes is used to
  # acknowledge all prompts.
  - yes '' | pecl install yaml
  # Tweak PHP configuration.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Build the code base. There is no lock file in the repo, so dependencies will
  # always be renegotiated.
  - composer install
  # Install on top of minimal for testing.
  - lightning install --no-dev --from-config "sqlite\://db.sqlite" minimal "http://127.0.0.1:8080"
  # Restore database fixture from the version we're testing and run database and
  # and Lightning config updates.
  - lightning update $VERSION

before_script:
  # If Lightning Dev is installed, uninstall it. It is no longer needed.
  - drush pm-uninstall --yes lightning_dev
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - chromedriver --port=4444 &
  - cp -f phpunit.xml ./docroot/core

script:
  - composer validate composer.json --no-check-all --ansi --no-interaction
  - phpunit --configuration ./docroot/core --group lightning_media
  - phpunit --configuration ./docroot/core tests/src/ExistingSite
  - phpunit --configuration ./docroot/core tests/src/ExistingSiteJavascript
  - behat

after_failure:
  - cd docroot
  - drush watchdog:show --count=100 --severity=Error --extended
