dist: trusty
language: php

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 7.1

env:
  - VERSION=HEAD
  - VERSION=3.2.0
  # The final CI slot should be used to test the update path from the oldest
  # available database fixture.
  - VERSION=1.0.0-rc2

addons:
  chrome: stable

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - google-chrome-stable --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, Behat, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1
  # Require Prestissimo to speed up Composer.
  - composer global require hirak/prestissimo

  # Install the PECL YAML extension for strict parsing. yes is used to
  # acknowledge all prompts.
  - yes '' | pecl install yaml
  # Tweak PHP configuration.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # Build the code base. There is no lock file in the repo, so dependencies will
  # always be renegotiated.
  - composer install
  # Install on top of minimal for testing.
  - lightning install --no-dev --from-config "sqlite\://db.sqlite" minimal "http://127.0.0.1:8080"
  # Restore database fixture from the version we're testing and run database and
  # and Lightning config updates.
  - lightning update $VERSION
  - cp -f phpunit.xml docroot/core

before_script:
  # Remove any time zone stored in config by the update path.
  - drush config:set system.date timezone.default '' --yes
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  - drush pm-enable lightning_roles toolbar --yes
  - chromedriver --port=4444 &

script:
  - composer validate composer.json --no-check-all --ansi --no-interaction
  - phpunit --debug --configuration ./docroot/core --group lightning_workflow
  - phpunit --debug --configuration ./docroot/core tests/src/ExistingSite
  - behat

after_failure:
  - cd docroot
  - drush watchdog:show --count=100 --severity=Error --extended
